# Generated by Django 4.2.7 on 2023-12-14 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eapp", "0002_alter_product_product_image_cartitem_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="item",
            new_name="item_name",
        ),
    ]
